apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-container
        image: nginx:1.7.9
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
spec:
  rules:
  - host: hello.diffus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-world-service
          servicePort: 80
