apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image: containous/traefik
        name: traefik-ingress-lb
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            hostPort: 80
          - name: https
            containerPort: 443
            hostPort: 443
          - name: http-alt
            containerPort: 8080
            hostPort: 8080
          - name: admin
            containerPort: 8081
#        volumeMounts:
#          - mountPath: /etc/traefik
#            name: traefik-volume
#            readOnly: false
        args:
        - --web
        - -d
        - --web.address=:8081
        - --kubernetes
#        - --configFile=/etc/traefik/traefik.toml
#        - --logLevel=DEBUG
#      volumes:
#        - hostPath:
#            path: /etc/traefik
#          name: traefik-volume
